@startuml DFD_PatientRegistration

!includeurl https://raw.githubusercontent.com/ArmanAvanesyan/DFD-PlantUML/main/DFD_Level_1.puml
!$LEVEL="DFD Level 1"

startDfd("1. Регистрация пациента")

' External Entities
External(ePatient, "Пациент")
External(eReceptionist, "Ресепшн")

' Process
Process("Регистрация пациента")
    SubProcess(sp1, "1.0", "Регистрация пациента")

' Data Stores
DataStore(d1, "D1: Журнал пациентов\n(Excel)")
DataStore(d2, "D2: Скан-копии документов\n(Файловый сервер)")
DataStore(d3, "D3: Расширенная анкета\n(Excel)")
DataStore(d4, "D4: Учётные записи\n(AD/LDAP)")

' Data Flows
DataFlows()
    Flow(ePatient, sp1, "PII:\nФИО, дата рождения,\nтелефон, e-mail\n[Шифрование]\n@tag:PII")
    Flow(ePatient, sp1, "Адресные данные:\nпрописка, проживание\n[Шифрование]\n@tag:ADDRESS")
    Flow(ePatient, sp1, "Соц. данные:\nместо работы/учёбы\n[Шифрование]\n@tag:SOCIAL")
    Flow(ePatient, sp1, "Медицинская анкета:\nхронические заболевания\n[Шифрование, обезличивание]\n@tag:MEDICAL_SENSITIVE")
    Flow(ePatient, sp1, "Документы:\nпаспорт, страховой полис\n[Шифрование, доступ по ролям]\n@tag:DOCUMENT_SCAN")

    Flow(eReceptionist, sp1, "Инициирует регистрацию")

    Flow(sp1, d1, "Сохранение PII\n[Шифрование]\n@tag:PII")
    Flow(sp1, d2, "Скан-копии документов\n(PDF/JPG)\n[Шифрование, контроль доступа]\n@tag:DOCUMENT_SCAN")
    Flow(sp1, d3, "Анкеты и мед. данные\n[Шифрование, обезличивание]\n@tag:MEDICAL_SENSITIVE")
    Flow(sp1, d4, "Создание учётной записи\n[Хеширование паролей, аудит]\n@tag:ACCOUNT_CREDENTIALS")

endDfd()

@enduml
