@startuml DFD_AppointmentScheduling

!includeurl https://raw.githubusercontent.com/ArmanAvanesyan/DFD-PlantUML/main/DFD_Level_1.puml
!$LEVEL="DFD Level 1"

startDfd("2. Запись на приём")

' External Entities
External(ePatient, "Пациент")
External(eReceptionist, "Ресепшн")

' Main Process
Process("Запись на приём")
    SubProcess(sp21, "2.1", "Создание записи\nна приём")
    SubProcess(sp22, "2.2", "Заключение\nконтракта")

' Data Stores
DataStore(d1, "D1: Журнал записи\nна приём (Excel)")
DataStore(d2, "D2: Контракты\nс пациентами (PDF/JPG)")
DataStore(d3, "D3: Контактные данные\nпациентов (Excel)")

' Data Flows
DataFlows()
    Flow(ePatient, sp21, "ФИО, дата и время\nжелаемого приёма")
    Flow(ePatient, sp21, "Контактные данные:\nтелефон, e-mail")
    Flow(sp21, d1, "Сохранение записи:\nФИО + дата/время приёма")
    Flow(sp21, d3, "Сохранение контактов")

    Flow(eReceptionist, sp21, "Вводит данные\nв расписание")

    Flow(ePatient, sp22, "Полис или паспорт")
    Flow(eReceptionist, sp22, "Оформляет контракт")
    Flow(sp22, d2, "Скан или копия\nдоговора/полиса")

endDfd()

@enduml
